# Uncomment if "rakefile not found" error
# language: generic

# Need super level permissions to execute build
sudo: required
# Install services
services:
    - docker
# Execute commands before tests are ran
before_install:
    - docker build -t seanparmesan/docker -f Dockerfile.dev .

script:
    - docker run -e CI=true seanparmesan/docker npm run test